name: Vanztec Rathole Client
slug: rathole_client
version: "0.1.3"
description: Secure tunnel client to connect Home Assistant to Vanztec cloud.
url: https://github.com/rapiz1/rathole

# 只声明你真正支持的架构（和 build.yaml 一致）
arch:
  - amd64
  - aarch64

startup: application
boot: auto

host_network: false
ingress: false

# 默认配置（UI 中的初始值）
options:
  vps_host: "43.153.44.119"
  vps_port: 7000
  client_id: "c001"
  token: "CHANGE_ME_STRONG"
  ha_local: "homeassistant:8123"

# UI 校验规则（bashio::config 正是读这里）
schema:
  vps_host: str
  vps_port: port
  client_id: str
  token: password
  ha_local: str
