name: Vanztec Rathole Client
slug: rathole_client
version: "0.1.3"
description: Secure tunnel client to connect Home Assistant to Vanztec cloud.
url: https://github.com/ytfangh/vanztec-ha-addons

arch:
  - amd64
  - aarch64

startup: application
boot: auto
host_network: false
ingress: false

# ✅ 关键：放在 manifest 里，Supervisor 才会注入 BUILD_FROM
build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19

options:
  vps_host: "43.153.44.119"
  vps_port: 7000
  client_id: "c001"
  token: "CHANGE_ME_STRONG"
  ha_local: "homeassistant:8123"

schema:
  vps_host: str
  vps_port: port
  client_id: str
  token: password
  ha_local: str
